#### Internal ####


#' Return response from a SODA request
#'
#' Return response from a SODA request
#'
#' @import httr
#' @export
#' @param request a SODA request
#' @param ... dot-dot-dot, ignore
response.soda <- function(request, ...){
  user <- attributes(request)$user
  password <- attributes(request)$password
  httr::GET(httr::build_url(request),
            `if`(is.null(user), NULL, httr::authenticate(user = user, password = password))
  )
}


#' Return content of response from a SODA request
#'
#' @import httr
#' @export
#' @param request a SODA request
#' @param ... dot-dot-dot, ignored
response_content.soda <- function(request, ...){
  httr::content(response.soda(request), "text")
}


#' Retrieve and parse a SODA response as data frame
#'
#' @import jsonlite
#' @export
#' @param x a SODA request
#' @param ... dot-dot-dot, ignored
as_data_frame.soda <- function(x, ...){
  request <- x
  as.data.frame.list(jsonlite::fromJSON(response_content.soda(request)))
}


#' Check if request uses plain SoQL query string
#'
#' A plain query is contrasted with parsed query generated by tidyish verbs, and will be placed in request$query$`query`
#'
#' @noRd
has_plain_query <- function(request){
  !is.null(request$query$`$query`)
}

#' If missing, add HTTP protocol to a URL
#'
#' @noRd
add_protocol <- function(url){
  if (!grepl("^http", url)) {url <- paste0("http://", url)}
  url
}


#' SODA Data Type Coersion Map
#'
#' @noRd
data_type <- list(checkbox = as.logical,
                  double = as.double,
                  floating_timestamp = lubridate::ymd_hms,
                  money = as.numeric,
                  number = as.numeric,
                  text = as.character)

